// import type { Metadata, Viewport } from "next";
// import "@/styles/globals.css";
// import { satoshi } from "@/styles/fonts";
// import TopBanner from "@/components/layout/Banner/TopBanner";
// import Footer from "@/components/layout/Footer";
// import HolyLoader from "holy-loader";
// import Providers from "./providers";
// import { Header } from "@/components/layout/Header/Header";
// import { CartSyncProvider } from "@/lib/CartSyncProvider";
// import ScrollToTop from "@/components/common/ScrollToTop";

// export const metadata: Metadata = {
//   title: "Shopco",
//   description: "Generated by create next app",
// };

// export const viewport: Viewport = {
//   themeColor: "#000000",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={satoshi.className}>
//         <ScrollToTop
//   threshold={500}
//   position="bottom-right"
//   showAfter={2000}
// />
//         <HolyLoader color="#2b77fb" />
//         <TopBanner />
//         <Providers>

//           {/* <TopNavbar /> */}
//           <Header/>
//           {children}

//         <CartSyncProvider />

//         </Providers>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import Providers from "./providers";
import { CartSyncProvider } from "@/lib/CartSyncProvider";
import ScrollToTop from "@/components/common/ScrollToTop";
import ConditionalLayout from "@/components/layout/ConditionalLayout";

export const metadata: Metadata = {
  title: "NexMart",
  description: "Modern ecommerce platform built with Next.js",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <ScrollToTop threshold={500} position="bottom-right" showAfter={2000} />
        {/* Providers يجب أن يبقى هنا (client providers داخلهم) */}
        <Providers>
          {/* ConditionalLayout هو Client component يتولى إظهار/hide الـ banner/header/footer */}
          <ConditionalLayout>{children}</ConditionalLayout>

          {/* Cart sync provider يمكن أن يكون داخل Providers أو بعد الـ ConditionalLayout حسب حاجتك */}
          <CartSyncProvider />
        </Providers>
      </body>
    </html>
  );
}
