import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";
import Providers from "./providers";
import { Header } from "@/components/layout/Header/Header";
import { CartSyncProvider } from "@/lib/CartSyncProvider";
import ScrollToTop from "@/components/common/ScrollToTop";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <ScrollToTop
  threshold={500}
  position="bottom-right"
  showAfter={2000}
/>
        <HolyLoader color="#2b77fb" />
        <TopBanner />
        <Providers>

          {/* <TopNavbar /> */}
          <Header/>
          {children}

        <CartSyncProvider />

        </Providers>
        <Footer />
      </body>
    </html>
  );
}
